api_version = "2025-04"

[[extensions]]
name = "t:name"
handle = "bfcm2025"
type = "function"
uid = "11a5a5aa-5d05-aab5-1e00-eb38a16723fec5f297ad"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart_lines_discounts_generate_run"

  [[extensions.targeting]]
  target = "cart.delivery-options.discounts.generate.run"
  input_query = "src/cart_delivery_options_discounts_generate_run.graphql"
  export = "cart_delivery_options_discounts_generate_run"

  [extensions.build]
  command = "cargo build --target=wasm32-unknown-unknown --release"
  path = "target/wasm32-unknown-unknown/release/bfcm2025.wasm"
  watch = [ "src/**/*.rs" ]
