api_version = "2025-04"

[[extensions]]
name = "t:name"
handle = "at-bfcm2025"
type = "function"
uid = "9b6cf006-b4e5-b49a-ac08-589d6a5e259035bb058a"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart_lines_discounts_generate_run"

  [extensions.build]
  command = "cargo build --target=wasm32-unknown-unknown --release"
  path = "target/wasm32-unknown-unknown/release/at-bfcm2025.wasm"
  watch = [ "src/**/*.rs" ]
